[package]
name = "compare-aws-sdk-s3"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
aws-sdk-s3 = { version = "=1.143.0", default-features = false, features = ["behavior-version-latest", "default-https-client", "http-1x", "rt-tokio", "rustls"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
